/**
 * Merges the runtime-coverage fragments into one Markdown report (P-008 gap 2, MVP).
 *
 * Runs as Playwright's `globalTeardown` (wired in `playwright.config.js`), so a `npm run
 * test:e2e` produces `test_data/TestResult/PhaseUI/coverage-<date>.md` plus a one-line
 * stdout summary. It is a *report*, never a gate: it cannot fail a run. What it is for:
 * turning "which e2e scenario touched which module, and did the registered handlers ever
 * fire" from nobody's guess into a list, so the next dead-code cleanup (P-010) has a
 * machine-written candidate set instead of a human reading 33 modules.
 *
 * Reading the output honestly: "0 listeners registered" is only suspicious for an
 * *interactive* module - pure helpers and config leaves (`modules/utils/*`, api-config,
 * kie-config, api-state, preview-state) legitimately register none. "registered > 0" with
 * "fired = 0" means this suite never exercised that path; it does not mean the path is dead.
 */

const fs = require('fs');
const path = require('path');

// frontend/tests/e2e/helpers -> frontend/
const FRONTEND_DIR = path.join(__dirname, '..', '..', '..');
const OUT_DIR = path.join(FRONTEND_DIR, '..', 'test_data', 'TestResult', 'PhaseUI');
const FRAGMENT_DIR = path.join(OUT_DIR, 'coverage-fragments');

function walkJs(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walkJs(full));
    else if (entry.name.endsWith('.js')) out.push(full);
  }
  return out;
}

/** Module paths relative to `frontend/` - the same shape the recorder records. */
function modulesOnDisk() {
  return walkJs(path.join(FRONTEND_DIR, 'modules'))
    .map((file) => path.relative(FRONTEND_DIR, file).split(path.sep).join('/'))
    .sort();
}

function readFragments() {
  if (!fs.existsSync(FRAGMENT_DIR)) return [];
  return fs
    .readdirSync(FRAGMENT_DIR)
    .filter((name) => name.endsWith('.json'))
    .map((name) => {
      try {
        return JSON.parse(fs.readFileSync(path.join(FRAGMENT_DIR, name), 'utf8'));
      } catch (err) {
        console.log(`[coverage] unreadable fragment ${name}: ${err.message}`);
        return null;
      }
    })
    .filter(Boolean);
}

function shortLoaded(urls, modules) {
  const loaded = new Set();
  for (const url of urls) {
    const match = /\/frontend\/((?:modules|shared)\/[\w./-]+\.js|app\.js)/.exec(url);
    if (match) loaded.add(match[1]);
  }
  return { loaded, missing: modules.filter((mod) => !loaded.has(mod)) };
}

function aggregate(fragments, modules) {
  const byModule = new Map(modules.map((mod) => [mod, { registered: 0, fired: 0, events: new Set() }]));
  const loadedUrls = new Set();
  const errors = [];
  for (const fragment of fragments) {
    for (const url of fragment.loaded || []) loadedUrls.add(url);
    for (const error of fragment.errors || []) errors.push({ test: fragment.title, error });
    for (const listener of fragment.listeners || []) {
      const bucket = byModule.get(listener.module) || { registered: 0, fired: 0, events: new Set() };
      bucket.registered += 1;
      bucket.fired += listener.fired || 0;
      bucket.events.add(listener.event);
      byModule.set(listener.module, bucket);
    }
  }
  return { byModule, ...shortLoaded(loadedUrls, modules), errors };
}

function directoryRollup(byModule) {
  const byDir = new Map();
  for (const [mod, bucket] of byModule) {
    const dir = mod.includes('/') ? mod.slice(0, mod.lastIndexOf('/')) : '(app.js / unattributed)';
    const row = byDir.get(dir) || { modules: 0, registered: 0, fired: 0, inert: 0 };
    row.modules += 1;
    row.registered += bucket.registered;
    row.fired += bucket.fired;
    if (bucket.registered === 0) row.inert += 1;
    byDir.set(dir, row);
  }
  return [...byDir].sort((a, b) => a[0].localeCompare(b[0]));
}

function renderReport(fragments, modules, stamp) {
  const { byModule, missing, errors } = aggregate(fragments, modules);
  const withListeners = [...byModule].filter(([, bucket]) => bucket.registered > 0);
  const neverFired = withListeners.filter(([, bucket]) => bucket.fired === 0);
  const inert = [...byModule].filter(([, bucket]) => bucket.registered === 0);
  const lines = [
    `# e2e runtime coverage (${stamp})`,
    '',
    `Merged ${fragments.length} fragment(s) from \`npm run test:e2e\`. Generated by`,
    '`frontend/tests/e2e/helpers/coverage-report.js` (Playwright globalTeardown).',
    '**This is a report, not a gate** - it can never fail a run (P-008 gap 2, MVP).',
    '',
    '## 1. Module loading',
    '',
    `- modules on disk: ${modules.length}; loaded in this run: ${modules.length - missing.length}`,
    missing.length ? `- **never loaded**: ${missing.map((m) => `\`${m}\``).join(', ')}` : '- never loaded: none',
    '',
    '## 2. DOM listener coverage (per module)',
    '',
    '| module | listeners registered | listener invocations | events |',
    '|---|---|---|---|',
    ...[...byModule]
      .sort((a, b) => b[1].registered - a[1].registered || a[0].localeCompare(b[0]))
      .map(([mod, bucket]) =>
        `| \`${mod}\` | ${bucket.registered} | ${bucket.fired} | ${[...bucket.events].sort().join(', ')} |`),
    '',
    '如何读这张表：`registered = 0` 只对**交互型**模块可疑——纯函数与配置叶模块（`modules/utils/*`、',
    'api-config、kie-config、api-state、preview-state）本来就不注册监听器；`registered > 0` 且',
    '`fired = 0` 表示**本次 e2e 从未走到那条路径**（不等于该死）。',
    '',
    `- 注册过监听器的模块：${withListeners.length} / ${modules.length}`,
    `- 注册了但一次都没触发：${neverFired.length}${neverFired.length ? `（${neverFired.map(([m]) => `\`${m}\``).join(', ')}）` : ''}`,
    `- 零监听器（需人工判断是否本就不需要）：${inert.length}`,
    '',
    '## 3. 按目录聚合（启发式，域号见 module-map §3）',
    '',
    '| 目录 | 模块数 | 零监听器 | 注册 | 触发 |',
    '|---|---|---|---|---|',
    ...directoryRollup(byModule).map(
      ([dir, row]) => `| \`${dir}\` | ${row.modules} | ${row.inert} | ${row.registered} | ${row.fired} |`,
    ),
    '',
    '## 4. Runtime errors',
    '',
    errors.length ? '| test | error |' : '_none_',
    ...(errors.length ? ['|---|---|', ...errors.map((e) => `| ${e.test} | ${e.error.replace(/\|/g, '\\|')} |`)] : []),
    '',
  ];
  return {
    markdown: lines.join('\n'),
    summary: `${modules.length - missing.length}/${modules.length} modules loaded, ` +
      `${withListeners.length} module(s) registered listeners, ` +
      `${neverFired.length} registered-but-never-fired, ${errors.length} runtime error(s)`,
    neverFired,
  };
}

module.exports = async function globalTeardown() {
  const fragments = readFragments();
  if (!fragments.length) {
    console.log('[coverage] no fragments found; report skipped (did the specs keep their import swap?)');
    return;
  }
  const stamp = new Date().toISOString().slice(0, 10);
  const { markdown, summary } = renderReport(fragments, modulesOnDisk(), stamp);
  fs.mkdirSync(OUT_DIR, { recursive: true });
  const outFile = path.join(OUT_DIR, `coverage-${stamp}.md`);
  fs.writeFileSync(outFile, markdown, 'utf8');
  console.log(`[coverage] ${summary} -> ${path.relative(process.cwd(), outFile)}`);
};

module.exports.renderReport = renderReport;
module.exports.modulesOnDisk = modulesOnDisk;
module.exports.readFragments = readFragments;
module.exports.FRAGMENT_DIR = FRAGMENT_DIR;
