"""Tests for document type classifier."""

from pathlib import Path

from app.services.document_type_classifier import classify_document

_SCRIPT_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parents[1]

_COI_FIXTURES = [
    "coi_acord25_synth_green.pdf",
    "coi_acord25_synth_yellow.pdf",
    "coi_acord25_cornell_sample.pdf",
    "coi_acord25_tampa_sample.pdf",
]

_ID_CARD_FIXTURES = ["id_card_synthetic_sample.pdf"]

_PICO_FIXTURES = [
    "pub_bmc_PMC10685505.pdf",
    "pub_springer_PMC10719124.pdf",
    "pub_bmcmed_PMC13613656.pdf",
    "pub_bmcpubh_PMC13595506.pdf",
    "pub_plosone_PMC13618946.pdf",
]


def test_classify_invoice_text() -> None:
    result = classify_document("", text_hint="Invoice Number INV-001 Bill To Customer")
    assert result["document_type"] == "invoice"
    assert result["confidence"] > 0


def test_classify_coi_text() -> None:
    result = classify_document(
        "",
        text_hint=(
            "CERTIFICATE OF LIABILITY INSURANCE. THIS CERTIFICATE IS ISSUED AS "
            "A MATTER OF INFORMATION ONLY AND CONFERS NO RIGHTS UPON THE "
            "CERTIFICATE HOLDER."
        ),
    )
    assert result["document_type"] == "coi"
    assert result["confidence"] > 0


def test_classify_coi_fixtures_file_level() -> None:
    # P-030b X6 bidirectional regression, positive arm: every committed ACORD
    # 25 fixture must classify as coi from its page-1 text layer.
    for name in _COI_FIXTURES:
        path = _PROJECT_ROOT / "test_data" / "testfiles" / "coi" / name
        result = classify_document(str(path))
        assert result["document_type"] == "coi", f"{name}: {result}"


def test_classify_pico_text() -> None:
    result = classify_document(
        "",
        text_hint=(
            "This randomized controlled trial assessed the primary outcome. "
            "Patients were given placebo in a double-blind design."
        ),
    )
    assert result["document_type"] == "pico"
    assert result["confidence"] > 0


def test_classify_pico_fixtures_file_level() -> None:
    # P-031 X1 bidirectional regression, positive arm: every committed OA RCT
    # fixture (the calibration corpus C1) must classify as pico from its
    # page-1 text layer.
    for name in _PICO_FIXTURES:
        path = _PROJECT_ROOT / "test_data" / "testfiles" / "pico" / name
        result = classify_document(str(path))
        assert result["document_type"] == "pico", f"{name}: {result}"


def test_classify_id_card_text() -> None:
    result = classify_document(
        "",
        text_hint="DRIVER LICENSE  DL N0: S1234567  DATE OF BIRTH: 01-JAN-1990  EXPIRES: 01-JAN-2030",
    )
    assert result["document_type"] == "id_card"
    assert result["confidence"] > 0


def test_classify_id_card_text_british_spelling() -> None:
    result = classify_document(
        "",
        text_hint="DRIVING LICENCE  DATE OF BIRTH: 01-JAN-1990  EXPIRES: 01-JAN-2030",
    )
    assert result["document_type"] == "id_card"
    assert result["confidence"] > 0


def test_classify_id_card_fixtures_file_level() -> None:
    # Synthetic (no real PII) driver-license-style fixture; generated by
    # test_data/scripts/generate_general_testfiles_pure.mjs.
    for name in _ID_CARD_FIXTURES:
        path = _PROJECT_ROOT / "test_data" / "testfiles" / "id_card" / name
        result = classify_document(str(path))
        assert result["document_type"] == "id_card", f"{name}: {result}"
        assert result["confidence"] > 0, f"{name}: {result}"


def test_single_keyword_hit_does_not_suggest() -> None:
    # 2026-10-08 hardening: one keyword hit with zero competition must not
    # surface as a 100%-confident suggestion (the bare-"license" lesson).
    result = classify_document("", text_hint="thank you for your business")
    assert result["document_type"] == "auto"
    assert result["confidence"] == 0.0


def test_classify_license_wording_does_not_suggest_id_card() -> None:
    # The observed false positives: generic "license" wording on non-ID pages.
    for hint in (
        "This is an open access article under the CC BY license",
        "LICENSE NUMBER: CGC1529884  properly licensed and insured subcontractors",
        "Software license renewal 890.00",
    ):
        result = classify_document("", text_hint=hint)
        assert result["document_type"] != "id_card", hint
        assert result["confidence"] == 0.0, hint


def test_classifier_non_coi_outputs_unchanged_vs_pre_coi_baseline() -> None:
    # P-030b X6 bidirectional regression, negative arm: non-COI documents keep
    # their exact pre-coi outputs (type AND confidence). Re-pinned 2026-10-08
    # for the bare-"license" narrowing: coi_negative_fl_exemption.pdf (a
    # workers-compensation exemption letter whose only hit was the contractor
    # "LICENSE NUMBER") and transaction_ledger_unbordered.pdf (software
    # license renewal) are id_card 1.0 false positives and now classify auto;
    # invoice_line_items_sample.pdf keeps type invoice, confidence 0.667 -> 1.0.
    expected = {
        ("coi", "coi_negative_fl_exemption.pdf"): ("auto", 0.0),
        ("GeneralFiles", "transaction_ledger_unbordered.pdf"): ("auto", 0.0),
        ("invoices", "invoice_line_items_sample.pdf"): ("invoice", 1.0),
        ("pdf", "cosent-form-test-document.pdf"): ("receipt", 1.0),
        ("pdf", "financial_report.pdf"): ("auto", 0.0),
        ("pdf", "sample-layout.pdf"): ("auto", 0.0),
        ("pdf", "sample_report.pdf"): ("auto", 0.0),
        ("invoices", "invoice_sample_01.pdf"): ("auto", 0.0),
    }
    for (subdir, name), (doc_type, confidence) in expected.items():
        path = _PROJECT_ROOT / "test_data" / "testfiles" / subdir / name
        result = classify_document(str(path))
        assert result["document_type"] == doc_type, f"{name}: {result}"
        assert result["confidence"] == confidence, f"{name}: {result}"
