"""Export LiteResult payloads to Markdown and Word."""

from __future__ import annotations

import io
import json
from typing import Any, Dict, List


def export_lite_to_json(result: Dict[str, Any], pretty: bool = True) -> str:
    if pretty:
        return json.dumps(result, ensure_ascii=False, indent=2)
    return json.dumps(result, ensure_ascii=False)


def export_lite_to_markdown(result: Dict[str, Any]) -> str:
    inp = result.get("input") or {}
    routing = result.get("routing") or {}
    quality = result.get("quality") or {}
    lines: List[str] = []

    filename = inp.get("filename") or "Document"
    lines.append(f"# {filename}")
    lines.append("")
    lines.append("## Document Information")
    lines.append("")
    lines.append("| Property | Value |")
    lines.append("| --- | --- |")
    lines.append(f"| File | {filename} |")
    lines.append(f"| Type | {inp.get('detected_file_type', 'N/A')} |")
    lines.append(f"| Pages | {inp.get('page_count', 'N/A')} |")
    lines.append(f"| Engine | {routing.get('engine_used', 'N/A')} |")
    lines.append(f"| Confidence | {quality.get('overall_confidence', 0):.0%} |")
    lines.append("")

    text = _collect_display_text(result)
    if text:
        lines.append("## Extracted Text")
        lines.append("")
        lines.append(text)
        lines.append("")

    tables = result.get("tables") or []
    if tables:
        lines.append("## Extracted Tables")
        lines.append("")
        for idx, table in enumerate(tables, start=1):
            lines.append(f"### Table {idx} (Page {table.get('page', '?')})")
            lines.append("")
            headers = table.get("headers") or []
            rows = table.get("rows") or []
            if headers:
                lines.append("| " + " | ".join(str(h) for h in headers) + " |")
                lines.append("| " + " | ".join(["---"] * len(headers)) + " |")
                for row in rows:
                    padded = row + [""] * (len(headers) - len(row)) if len(row) < len(headers) else row[: len(headers)]
                    lines.append("| " + " | ".join(str(c) for c in padded) + " |")
            elif rows:
                for row in rows:
                    lines.append("| " + " | ".join(str(c) for c in row) + " |")
            lines.append("")

    lines.append("---")
    lines.append("_Generated by DocuVision Lite_")
    return "\n".join(lines)


def export_lite_to_docx_bytes(result: Dict[str, Any]) -> bytes:
    try:
        from docx import Document
    except ImportError as exc:
        raise RuntimeError("Word export requires python-docx. Install: pip install python-docx") from exc

    inp = result.get("input") or {}
    routing = result.get("routing") or {}
    doc = Document()
    doc.add_heading(inp.get("filename") or "DocuVision Lite Result", level=0)

    doc.add_heading("Document Information", level=1)
    info = doc.add_paragraph()
    info.add_run(f"Type: {inp.get('detected_file_type', 'N/A')}\n")
    info.add_run(f"Pages: {inp.get('page_count', 'N/A')}\n")
    info.add_run(f"Engine: {routing.get('engine_used', 'N/A')}\n")

    text = _collect_display_text(result)
    if text:
        doc.add_heading("Extracted Text", level=1)
        doc.add_paragraph(text)

    tables = result.get("tables") or []
    if tables:
        doc.add_heading("Extracted Tables", level=1)
        for idx, table in enumerate(tables, start=1):
            doc.add_heading(f"Table {idx} (Page {table.get('page', '?')})", level=2)
            headers = table.get("headers") or []
            rows = table.get("rows") or []
            col_count = len(headers) if headers else (len(rows[0]) if rows else 0)
            if col_count == 0:
                continue
            table_el = doc.add_table(rows=1 + len(rows), cols=col_count)
            table_el.style = "Table Grid"
            if headers:
                for col_idx, header in enumerate(headers):
                    table_el.rows[0].cells[col_idx].text = str(header)
                start_row = 1
            else:
                start_row = 0
            for row_idx, row in enumerate(rows):
                for col_idx in range(col_count):
                    value = row[col_idx] if col_idx < len(row) else ""
                    table_el.rows[start_row + row_idx].cells[col_idx].text = str(value)

    buffer = io.BytesIO()
    doc.save(buffer)
    return buffer.getvalue()


def _collect_display_text(result: Dict[str, Any]) -> str:
    ocr = result.get("ocr") or []
    if ocr:
        blocks = sorted(
            ocr,
            key=lambda b: (b.get("page") or 1, (b.get("bbox") or [0, 0, 0, 0])[1], (b.get("bbox") or [0, 0, 0, 0])[0]),
        )
        return "\n".join(str(b.get("text") or "") for b in blocks if (b.get("text") or "").strip())
    preview = result.get("text_preview")
    return str(preview).strip() if preview else ""
